# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import calculadora as module_0


def test_case_0():
    int_0 = -492
    var_0 = module_0.divide(int_0, int_0)
    assert var_0 == pytest.approx(1.0, abs=0.01, rel=0.01)
    bool_0 = False
    var_1 = module_0.multiplica(bool_0, bool_0)
    assert var_1 == 0
    none_type_0 = None
    with pytest.raises(ValueError):
        module_0.divide(none_type_0, var_1)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -1152
    dict_0 = {int_0: int_0}
    list_0 = [dict_0, int_0]
    module_0.divide(list_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    var_0 = module_0.suma(bool_0, bool_0)
    assert var_0 == 2
    none_type_0 = None
    module_0.divide(bool_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = 1806.7836
    dict_0 = {float_0: float_0}
    float_1 = 1710.64
    module_0.multiplica(dict_0, float_1)
